In [1]:
import torch

 torch.arange(12) 创建了一个张量, 一个张量是可能有多个维度的数组

In [12]:
x.shape
# shape可以查看该张量的形状

<function Tensor.numel>

In [13]:
x.numel()
# numel()返回张量中元素的个数

12

In [16]:
x.reshape(3, 4)
# reshape返回将张量进行重构后的新张量

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
torch.zeros((2, 3, 4))
# zero 用于创建全0的数组

In [18]:
torch.tensor([[1, 2, 3],[3, 2, 1]])
# 固定的赋值

tensor([[1, 2, 3],
        [3, 2, 1]])

In [ ]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[1.0, 0, 0, 0],[2, 0, 0, 0], [3, 0, 0, 0]])
torch.cat((x, y), dim = 0), torch.cat((x, y), dim = 1)
# dim = 0, dim = 1, 从不同方位进行拼接, 最终结果会是dim指定的那个维度的数据不变(dim越小, 越靠近内部括号?), 其他改变

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  0.,  0.,  0.],
         [ 2.,  0.,  0.,  0.],
         [ 3.,  0.,  0.,  0.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  0.,  0.,  0.],
         [ 4.,  5.,  6.,  7.,  2.,  0.,  0.,  0.],
         [ 8.,  9., 10., 11.,  3.,  0.,  0.,  0.]]))

In [33]:
# 当两个维度相同, 形状不同的张量要相加时, 会调用广播机制: 少的维度复制自己, 知道等于多的维度, 必须是1才行?
a = torch.arange(4).reshape(4, 1)
b = torch.arange(2).reshape(1, 2)
a, b, a+b

(tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3],
         [3, 4]]))

In [38]:
x, x[-1], x[0:2, 1:3], x[:, 1:3]
# 数组取行列操作

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[1., 2.],
         [5., 6.]]),
 tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]))

In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')
    # python 文件操作, 可以看到真的创建了一个data文件夹. 里面有一个house_tiny.csv文件

In [3]:
# 我们通常使用pandas来进行数据处理
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [4]:
# 另一种形式, 直接输出data
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [ ]:
# 未知数据的处理
 # input为前两列的值, output为第三列的值
# fillna是指填补NaN的数据, 用input.mean填补, input.mean是已知数据的平均值
inputs, outputs = data.iloc[:, 0:1], data.iloc[:, 3]
inputs = inputs.fillna(inputs.mean()) # 新版pandas较为严格, 不允许不可求平均值的数据求平均值
print(inputs)

   NumRooms
0       3.0
1       2.0
2       4.0
3       3.0


In [20]:
# 对类别值或离散值的处理, 我们单独将NaN视为一个类别
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True) #这段函数将NaN单独分出来了
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [ ]:
# 经过上面的操作, 我们不仅处理了所有NaN值, 还将所有的值转化为了数值类型, 这样就方便我们将其转化为张量了
# pandas对象中数据类型是混合的或不是NumPy可以直接处理的类型（如字符串或Pandas特有的数据类型），则可能不会按预期工作
# 所以这里用to_numpy先转换成numpy数组格式
x, y = torch.tensor(inputs.to_numpy(dtype=float)), torch.tensor(outputs.to_numpy(dtype=float))
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))